### ISSUE TITLE
no method named `set_reuse_port` found for struct `Socket`

### ISSUE THREAD

**Issue by notrly1337** [fujita/tokio-reuseport#1]
Nice work, loved the article ! The latest version of does not compile, though.

Environment:
stable-x86_64-pc-windows-gnu (default)
rustc 1.54.0 (a178d0322 2021-07-26)

![image](https://user-images.githubusercontent.com/63503027/135730544-a581bffe-a18b-4fa7-9e9d-4e4bd1ebf91d.png)

However `tonic 0.5.2` compiles fine when included in an empty project:
![image](https://user-images.githubusercontent.com/63503027/135730628-83525928-6351-4049-9d9a-5c3c849656fa.png)

I also to compile the latest commit of Tonic from source and it worked.

Thanks !

**Comment by fujita** [comment]
Only Linux.
